### ISSUE TITLE
BUG ObjectCreatorPage::CreateForm creates new DataObjects as a singleton object without defaults set

### ISSUE THREAD

**Issue by JoshuaCarter** [nyeholt/silverstripe-frontend-objects#20]
https://github.com/nyeholt/silverstripe-frontend-objects/blob/f86a7e38425f37a54bb3cdb25ed3b4b8c83b6ef0/code/pages/ObjectCreatorPage.php#L510

A querk with the way SilverStripe instantiates objects means that this line will return a singleton without it's defaults initialised. This can be worked around by specifiying the singleton arg as false:

```
$this->editObject = $class::create(null, false);
```

Happy to PR if you want this change.

**Comment by nyeholt** [comment]
Yep, PR this please :)

**Comment by JoshuaCarter** [comment]
Solved by https://github.com/nyeholt/silverstripe-frontend-objects/pull/21
